---
version: '2.0'
services:

  db:
    restart: always
    image: postgres
    container_name: postgres
    expose:
    - '5432'
    ports:
    - 5432:5432
    volumes:
    - postgres-data-volume:/var/lib/postgresql/data

  simple_example:
    build: simple_example_for_dad/.
    container_name: simple_example
    entrypoint: "/bin/bash -c 'echo this_service_is_disabled'"
    volumes:
    - ./simple_example_for_dad/data:/tmp/log

volumes:
  postgres-data-volume:
    driver: local
